version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker-backend
    container_name: backend-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./.env
    networks:
      - app-network
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-img
    container_name: frontend-container
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true


networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local