export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_REGISTER_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_LOGIN_FAIL'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'


export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_PROFILE_REQUEST = 'USER_LIST_PROFILE_REQUEST'
export const USER_LIST_PROFILE_SUCCESS = 'USER_LIST_PROFILE_SUCCESS'
export const USER_LIST_PROFILE_FAIL = 'USER_LIST_PROFILE_FAIL'
export const USER_LIST_PROFILE_RESET = 'USER_LIST_PROFILE_RESET'

export const USER_REMOVE_PROFILE_REQUEST = 'USER_GET_PROFILE_REQUEST'
export const USER_REMOVE_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'
export const USER_REMOVE_PROFILE_FAIL = 'USER_GET_PROFILE_FAIL'


export const USER_GET_PROFILE_REQUEST = 'USER_GET_PROFILE_REQUEST'
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'
export const USER_GET_PROFILE_FAIL = 'USER_GET_PROFILE_FAIL'

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL'
export const UPDATE_USER_PROFILE_RESET = 'UPDATE_USER_PROFILE_RESET'
